config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc:
    dst: ~/.ssh/rc
    src: ssh/rc
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
profiles:
  remote:
    dotfiles:
    - f_screenrc
    - f_rc
  work:
    dotfiles:
    - d_doom.d
