# actions:
#   pre:
#     zplug-install: test -e ~/.zsh/zplug || (git clone https://github.com/zplug/zplug
#       ~/.zsh/zplug)
#   vim-plug: vim +PlugInstall +qall
#   zplug: (zsh -c "source ~/.zshrc && zplug install")
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc:
    dst: ~/.ssh/rc
    src: ssh/rc
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  vim:
    actions:
    - vim-plug
    dst: ~/.vimrc
    src: editors/vimrc
  zplug:
    actions:
    - zplug-install
    - zplug
    dst: ~/.zshrc
    src: prompt/zplug
profiles:
  remote:
    dotfiles:
    - f_screenrc
    - f_rc
    - vim
    include:
    - liquidprompt
  work:
    dotfiles:
    - vim
