actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload;
      curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    zplug-install: test -e ~/.zsh/zplug || (git clone https://github.com/zplug/zplug ~/.zsh/zplug)
  vim-plug: vim +PlugInstall +qall
  zplug: (zsh -c "source ~/.zshrc && zplug install")
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc:
    dst: ~/.ssh/rc
    src: ssh/rc
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  f_vimrc:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.vimrc
    src: vimrc
  f_zshrc:
    actions:
    - zplug-install
    - zplug
    dst: ~/.zshrc
    src: zshrc
profiles:
  remote:
    dotfiles:
    - f_screenrc
    - f_rc
  work:
    dotfiles:
    - f_vimrc
    - f_zshrc
