config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc:
    dst: ~/.ssh/rc
    src: ssh/rc
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
  d_zsh:
    src: zsh
    dst: ~/.zsh
    upignore:
    - '.hist_file'
    - '.z'
    - '.zsh-plugins.sh'
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  zsh:
    dotfiles:
    - d_zsh
    - f_zshrc
  remote:
    dotfiles:
    - f_screenrc
    - f_rc
  work:
    dotfiles:
    - d_doom.d
    include:
    - zsh
